name: Release Docker

on:
  workflow_dispatch:

env:
  DOCKER_IMAGE_SLIM: endresshauser/zephyr-box:1.0.2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push slim container
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE_SLIM }}
          file: zephyr-box/Dockerfile
